name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update repos
      shell: bash
      run: sudo apt-get update

    - name: Hold back grub-efi-amd64-signed # TODO: Remove temporary fix
      shell: bash
      run: sudo apt-mark hold grub-efi-amd64-signed
      
    - name: Upgrade system
      shell: bash
      run: sudo apt-get upgrade -y
    - name: Install git and GTK3
      shell: bash
      run: sudo apt-get install -y git tar libgtk-3-dev libadwaita-1-dev # libgtk4-layer-shell-dev
    - name: Build gtk4-layer-shell while it is not published on ubuntu
      shell: bash
      run: |
          sudo apt install meson libwayland-dev libgtk-4-dev gobject-introspection libgirepository1.0-dev gtk-doc-tools valac
          cd ..
          git clone https://github.com/wmww/gtk4-layer-shell.git
          cd gtk4-layer-shell
          meson setup -Dexamples=true -Ddocs=true -Dtests=true build
          ninja -C build
          sudo ninja -C build install
          sudo ldconfig
          cd ..
          cd gtk4-layer-shell-gir


    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
