name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache APT Packages
  # You may pin to the exact commit or the version.
  # uses: awalsh128/cache-apt-pkgs-action@7ca5f46d061ad9aa95863cd9b214dd48edef361d
      uses: awalsh128/cache-apt-pkgs-action@v1.5.0
      with:
        packages: cairo gtk4 atk glib gobject-introspection pango gdk-pixbuf graphene gtk4-layer-shell      
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
